Broken evaluation of "Requires.private: gmodule-no-export-2.0" in gio-2.0.pc ?
/usr/bin/ld: .../lib/libgio-2.0.so: undefined reference to `g_module_open_full'